"""add daily_ingest_snapshots

Revision ID: 312d29cec7cc
Revises: 02915d649b23
Create Date: 2026-07-18 11:36:05.058430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '312d29cec7cc'
down_revision: Union[str, None] = '02915d649b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_ingest_snapshots',
    sa.Column('publish_record_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('source_mode', sa.String(length=20), nullable=False),
    sa.Column('source_client', sa.String(length=100), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('favorites', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('private_message_count', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['publish_record_id'], ['video_publish_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publish_record_id', 'snapshot_date', 'source_mode', name='uq_ingest_record_date_mode')
    )
    with op.batch_alter_table('daily_ingest_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_ingest_snapshots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_ingest_snapshots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_ingest_snapshots_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_ingest_snapshots_publish_record_id'), ['publish_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_ingest_snapshots_snapshot_date'), ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_ingest_snapshots_source_mode'), ['source_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_ingest_snapshots_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_ingest_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_ingest_snapshots_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_ingest_snapshots_source_mode'))
        batch_op.drop_index(batch_op.f('ix_daily_ingest_snapshots_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_daily_ingest_snapshots_publish_record_id'))
        batch_op.drop_index(batch_op.f('ix_daily_ingest_snapshots_platform'))
        batch_op.drop_index(batch_op.f('ix_daily_ingest_snapshots_id'))
        batch_op.drop_index(batch_op.f('ix_daily_ingest_snapshots_created_at'))

    op.drop_table('daily_ingest_snapshots')
    # ### end Alembic commands ###
