"""TASK-013: AI内容中心 - 新增content_opportunities表

Revision ID: 4058907b66bc
Revises: d48d5fe20daf
Create Date: 2026-07-13 22:42:52.002768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4058907b66bc'
down_revision: Union[str, None] = 'd48d5fe20daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
