"""add actual_performance to growth_review_reports

Revision ID: 562444601be7
Revises: 312d29cec7cc
Create Date: 2026-07-18 11:42:34.722730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '562444601be7'
down_revision: Union[str, None] = '312d29cec7cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('growth_review_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_performance', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('growth_review_reports', schema=None) as batch_op:
        batch_op.drop_column('actual_performance')

    # ### end Alembic commands ###
