"""TASK-014: 主播智能画像引擎 - 升级creator_profiles,新增creator_preferences和scoring_configs表

Revision ID: 696cdda55266
Revises: 4058907b66bc
Create Date: 2026-07-13 22:57:02.681935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '696cdda55266'
down_revision: Union[str, None] = '4058907b66bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_configs',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('trend_weight', sa.Integer(), nullable=True),
    sa.Column('consult_weight', sa.Integer(), nullable=True),
    sa.Column('creator_weight', sa.Integer(), nullable=True),
    sa.Column('original_weight', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_scoring_configs_created_at'), 'scoring_configs', ['created_at'], unique=False)
    op.create_index(op.f('ix_scoring_configs_id'), 'scoring_configs', ['id'], unique=False)
    op.create_table('creator_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_weights', sa.JSON(), nullable=True),
    sa.Column('style_weights', sa.JSON(), nullable=True),
    sa.Column('score_weights', sa.JSON(), nullable=True),
    sa.Column('audience_profile', sa.JSON(), nullable=True),
    sa.Column('preferred_tags', sa.JSON(), nullable=True),
    sa.Column('avoided_tags', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_preferences_created_at'), 'creator_preferences', ['created_at'], unique=False)
    op.create_index(op.f('ix_creator_preferences_id'), 'creator_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_creator_preferences_user_id'), 'creator_preferences', ['user_id'], unique=True)
    op.add_column('creator_profiles', sa.Column('content_style', sa.JSON(), nullable=True))
    op.add_column('creator_profiles', sa.Column('speaking_style', sa.JSON(), nullable=True))
    op.add_column('creator_profiles', sa.Column('camera_style', sa.String(length=50), nullable=True))
    op.add_column('creator_profiles', sa.Column('editing_level', sa.String(length=50), nullable=True))
    op.add_column('creator_profiles', sa.Column('category_distribution', sa.JSON(), nullable=True))
    op.add_column('creator_profiles', sa.Column('audience_profile', sa.JSON(), nullable=True))
    op.add_column('creator_profiles', sa.Column('account_type', sa.String(length=50), nullable=True))
    op.add_column('creator_profiles', sa.Column('growth_stage', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creator_profiles', 'growth_stage')
    op.drop_column('creator_profiles', 'account_type')
    op.drop_column('creator_profiles', 'audience_profile')
    op.drop_column('creator_profiles', 'category_distribution')
    op.drop_column('creator_profiles', 'editing_level')
    op.drop_column('creator_profiles', 'camera_style')
    op.drop_column('creator_profiles', 'speaking_style')
    op.drop_column('creator_profiles', 'content_style')
    op.drop_index(op.f('ix_creator_preferences_user_id'), table_name='creator_preferences')
    op.drop_index(op.f('ix_creator_preferences_id'), table_name='creator_preferences')
    op.drop_index(op.f('ix_creator_preferences_created_at'), table_name='creator_preferences')
    op.drop_table('creator_preferences')
    op.drop_index(op.f('ix_scoring_configs_id'), table_name='scoring_configs')
    op.drop_index(op.f('ix_scoring_configs_created_at'), table_name='scoring_configs')
    op.drop_table('scoring_configs')
    # ### end Alembic commands ###
