"""add effect_config to video_edit_segments

Revision ID: aa266b3edc17
Revises: 562444601be7
Create Date: 2026-07-18 12:06:56.660447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa266b3edc17'
down_revision: Union[str, None] = '562444601be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_edit_segments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('effect_config', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_edit_segments', schema=None) as batch_op:
        batch_op.drop_column('effect_config')

    # ### end Alembic commands ###
