"""TASK-012.5: AI数据基础层完善 - 增强ai_tasks表,新增agents/creator_actions/content_metrics表

Revision ID: d48d5fe20daf
Revises: c5bb93227846
Create Date: 2026-07-13 22:10:54.546536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd48d5fe20daf'
down_revision: Union[str, None] = 'c5bb93227846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
